### PR TITLE
Add write.phyloXML() and corresponding tests

### PR DESCRIPTION
**Pull request by fmarotta**
Hi! This PR adds a function to export trees in [PhyloXML](https://en.wikipedia.org/wiki/PhyloXML) format (and some tests).

### CODE REVIEW

**Comment by emmanuelparadis** [comment]
Hi Federico,

This sounds interesting! Right now, a help page (*.Rd) is missing. Also we removed the `tests/` folder from the ape's sources because the tests take too long to run for CRAN: see the package [apeTests](https://github.com/emmanuelparadis/apeTests) where tests are now run.

There are some information on how to prepare contribution to ape on:

[https://emmanuelparadis.github.io/ape_development.html](https://emmanuelparadis.github.io/ape_development.html)

This needs a bit of updating (I'll add the point about `apeTests`). If possible too, I'll try to add information about adding dependencies: so far ape tries to use simple dependencies (i.e., R + recommended packages).

Best,

Emmanuel

**Comment by fmarotta** [comment]
Hi Emmanuel, thanks a lot for your reply!

I have moved the tests to the apeTests repository and added a .Rd file for documentation. This PR only adds one suggested dependency, xml2. We could live without it and create the XML elements with `paste()`, but it would be a bit uglier. Also, an XML-parsing package would be definitely needed if someone wants to implement `read.phyloXML()` in the future. Still, I will remove the dependency if you prefer so.

I have incremented the version from 5.8-0.1 to 5.8-1.0. I didn't find any info about the convention for minor versions and patches, so please let me know if the number is not correct.

Federico

**Comment by emmanuelparadis** [comment]
Hi Federico,

Sorry for taking so long to get back to this.

Many thanks for the updated PR. I added the changes manually because other changes were made in the meantime.
>This PR only adds one suggested dependency, xml2.

OK with that. We can see how it works.

>I have incremented the version from 5.8-0.1 to 5.8-1.0. I didn't find any info about the convention for minor versions and patches, so please let me know if the number is not correct.

Actually, it is explained on [another page](https://emmanuelparadis.github.io/ape_installation.html#github). No worry, I changed it to "Version: 5.8-0.4". I also adapted a few other files (you can add your ORCID number if you wish in the DESCRIPTION file).

I'll push everything here in a moment. [apeTests](https://github.com/emmanuelparadis/apeTests) has also been updated.

Cheers,

Emmanuel

**Comment by fmarotta** [comment]
Thank you Emmanuel!

**Pull request closed without merging**
