### PR TITLE
Add GitHub links to DESCRIPTION

### PR DESCRIPTION
**Pull request by maelle**
I myself had to do a bit of detective work a few weeks ago :work:

### CODE REVIEW

**Comment by emmanuelparadis** [comment]
Just in time! I'm packing ape 5.7-1 for CRAN. Thanks!

**Comment by maelle** [comment]
but you closed the PR, you didn't merge it?

**Comment by emmanuelparadis** [comment]
I added it directly the file. I'll push later :)

**Comment by maelle** [comment]
aaah ok! de rien :slightly_smiling_face:

**Pull request closed without merging**
